--# change lanusau:1 Test change number 1
ALTER TABLE advantage.wps_device
add (
    provider_device_status_m         VARCHAR2(50),
    provider_device_status_date_m    DATE,
    provider_device_status_v         VARCHAR2(50),
    provider_device_status_date_v    DATE,
    reason_code_m                    VARCHAR2(100),
    reason_code_v                    VARCHAR2(100),
    meid                             VARCHAR2(250),
    port_in_flag                     NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    byod_flag                        NUMBER(1, 0)      DEFAULT 0 NOT NULL,
    byod_manufacturer                VARCHAR2(500),
    byod_model                       VARCHAR2(500)
)
;    
COMMENT ON COLUMN advantage.wps_device.provider_device_status_m IS 'Device status with provider for Messaging - SUSPEND,RESUME'
;
COMMENT ON COLUMN advantage.wps_device.provider_device_status_date_m IS 'When provider status was updated for Messaging'
;
COMMENT ON COLUMN advantage.wps_device.provider_device_status_v IS 'Device status with provider for Voice- SUSPEND,RESUME'
;
COMMENT ON COLUMN advantage.wps_device.provider_device_status_date_v IS 'When provider status was updated for Voice'
;
COMMENT ON COLUMN advantage.wps_device.reason_code_m IS 'Reson code for Messaging - Rhinoboot_0_m, provision_m, etc'
;
COMMENT ON COLUMN advantage.wps_device.reason_code_v IS 'Reson code for Voice - Rhinoboot_0_v, provision_v, etc'
;
COMMENT ON COLUMN advantage.wps_device.meid IS 'Mobile Equipment Identifier for BYOD'
;
COMMENT ON COLUMN advantage.wps_device.port_in_flag IS 'Flag whether phone was ported into us, 1 - yes, 0 - no'
;
COMMENT ON COLUMN advantage.wps_device.byod_flag IS '1-for own device, 0-not own device'
;
COMMENT ON COLUMN advantage.wps_device.byod_manufacturer IS 'Manufacturer for BYOD'
;
COMMENT ON COLUMN advantage.wps_device.byod_model IS 'Phone model for BYOD'
;

--#rollback
ALTER TABLE advantage.wps_device
drop (
    provider_device_status_m,
    provider_device_status_date_m,
    provider_device_status_v,
    provider_device_status_date_v,
    reason_code_m,
    reason_code_v,
    meid,
    port_in_flag,
    byod_flag,
    byod_manufacturer,
    byod_model
)
;

--#change lanusau:2 Test change number 2
--#ifnot select count(*) from dba_tablespaces where tablespace_name = 'WPS_DATA'
CREATE TABLESPACE wps_data datafile size 100M
;
--#endif
CREATE TABLE advantage.wps_device_port_in(
    device_port_in_id    NUMBER(38, 0)     NOT NULL,
    device_order_id      NUMBER(38, 0),
    mdn                  VARCHAR2(100)     NOT NULL,
    authorized_by        VARCHAR2(4000),
    pin                  VARCHAR2(100),
    message_id           VARCHAR2(500),
    port_id              VARCHAR2(500),
    port_status          VARCHAR2(500),
    port_request_type    VARCHAR2(500),
    due_date             DATE,
    reason_code          VARCHAR2(500),
    create_sysdate       DATE              NOT NULL,
    update_sysdate       DATE              NOT NULL,
    user_update          VARCHAR2(1000),
    comments             VARCHAR2(2000)
)
TABLESPACE wps_data
;

COMMENT ON COLUMN advantage.wps_device_port_in.device_port_in_id IS 'Primary key'
;
COMMENT ON COLUMN advantage.wps_device_port_in.device_order_id IS 'Primary key'
;
COMMENT ON COLUMN advantage.wps_device_port_in.mdn IS 'MDN'
;
COMMENT ON COLUMN advantage.wps_device_port_in.authorized_by IS 'Who authorized the PORT IN request'
;
COMMENT ON COLUMN advantage.wps_device_port_in.pin IS 'PIN that was provided'
;
COMMENT ON COLUMN advantage.wps_device_port_in.message_id IS 'Message Id of original Port Out Request'
;
COMMENT ON COLUMN advantage.wps_device_port_in.port_id IS 'Unique key generated by NPS to identify port'
;
COMMENT ON COLUMN advantage.wps_device_port_in.port_status IS 'Status of the port '
;
COMMENT ON COLUMN advantage.wps_device_port_in.port_request_type IS 'PortIn/PortOut to be used for query messages in the queue'
;
COMMENT ON COLUMN advantage.wps_device_port_in.due_date IS 'Due date'
;
COMMENT ON COLUMN advantage.wps_device_port_in.reason_code IS 'Reason associated with the response type.'
;
COMMENT ON COLUMN advantage.wps_device_port_in.create_sysdate IS 'Timestamp when record was created'
;
COMMENT ON COLUMN advantage.wps_device_port_in.update_sysdate IS 'Timestamp when record was last updated'
;
COMMENT ON COLUMN advantage.wps_device_port_in.user_update IS 'Information about user that updated the record'
;
COMMENT ON COLUMN advantage.wps_device_port_in.comments IS 'Free form comments'
;

CREATE UNIQUE INDEX advantage.wps_device_port_in_u1 ON advantage.wps_device_port_in(device_port_in_id)
TABLESPACE wps_index
;

--#rollback
DROP TABLE advantage.wps_device_port_in
;
